### ISSUE TITLE
openwec.conf.sample.toml doesn't show how to configure multiple listeners

### ISSUE THREAD

**Issue by a139786** [cea-sec/openwec#132]
```
# You may define multiple collect servers.
# Each collector must listen on a different (address, port) pair.
# All collectors share the same database.
# This is useful if you want to support both Kerberos and TLS authentication
```
clearly states it's a possibility but doesn't make it clear how to do this. (This is exactly the scenario I'm attempting to use, with Kerberos for domain-joined so I don't need to use the shirtshow that is ADCS and cert-based (TLS) auth for non-domain-joined.)

**Comment by vruello** [comment]
Hi @a139786!

`collectors` is an array of tables (https://toml.io/en/v1.0.0#array-of-tables). You can define it multiple times. Look at the following example:

```toml
[server]
keytab = "wec.windomain.local.keytab"

[database]
type = "SQLite"
path = "/tmp/db.sqlite"

[[collectors]]
hostname = "wec.windomain.local"
listen_address = "0.0.0.0"
listen_port = 5986

[collectors.authentication]
type = "Tls"
ca_certificate = "ca-cert.pem"
server_certificate = "server-cert.pem"
server_private_key = "server-key.pem"

[[collectors]]
hostname = "wec.windomain.local"
listen_address = "0.0.0.0"
listen_port = 5985

[collectors.authentication]
type = "Kerberos"
service_principal_name = "http/wec.windomain.local@WINDOMAIN.LOCAL"
```

`openwec` server will listen on `0.0.0.0:5985` (and expect http and Kerberos authentication there) and on `0.0.0.0:5986` (and expect https and TLS certificate authentication there).
